blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/keepittechie/dtrust#readme
    about: Please check the README before filing an issue.
  - name: Discussions
    url: https://github.com/keepittechie/dtrust/discussions
    about: For questions or brainstorming ideas.
